### ISSUE TITLE
ConnectionError: Error 111 connecting to None:6379. Connection refused.

### ISSUE THREAD

**Issue by FlowFX** [FlowFX/unkenmathe.de#190]
View details in Rollbar: [https://rollbar.com/flowfx/Unkenmathe/items/33/](https://rollbar.com/flowfx/Unkenmathe/items/33/)

```
Traceback (most recent call last):
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/views.py", line 133, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/views.py", line 79, in dispatch
    **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/views.py", line 101, in post
    if form.is_valid():
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/forms.py", line 159, in clean
    **credentials)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/adapter.py", line 482, in authenticate
    self.pre_authenticate(request, **credentials)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/allauth/account/adapter.py", line 469, in pre_authenticate
    login_data = cache.get(cache_key, None)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django_redis/cache.py", line 40, in _decorator
    raise e.parent
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/django_redis/client/default.py", line 201, in get
    value = client.get(key)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/flowfx/.virtualenvs/unkenmathe.de/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to None:6379. Connection refused.
```

**Comment by FlowFX** [comment]
Looks like Redis is still not configured correctly. Test it in local dev environment!
